name: Bug Report
description: File a bug report to help us improve
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop or paste images here

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other

  - type: dropdown
    id: os
    attributes:
      label: What OS are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment information
      placeholder: |
        - Node.js version: [e.g. 18.x]
        - Azure UI version: [e.g. 1.0.0]
        - Azure Services: [Service Bus, Cosmos DB]

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, paste any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you confirm that
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided all the requested information
          required: true
