name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered
      placeholder: Have you considered any other approaches?

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Describe how this feature would be used and who would benefit
      placeholder: This feature would help users who...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you confirm that
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: I understand this is a volunteer-driven project
          required: true
